apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: this-or-that-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rohanworld101/yesno-frontend:4fb72ed
          imagePullPolicy: Always
          ports:
            - containerPort: 80

