apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: this-or-that-argocd
spec:
  type: NodePort   # 🔥 THIS IS KEY
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008   # use this port
